// lib/projects-data.js

export const projects = [
 
  {
    id: "project-054",
    slug: "hitachi-hvdc-valve-factory",
    categoryType: [
      "Architectural & Interior",
      "Civil & Infrastructure",
      "Structural Engineering",
      "BIM & MEP",
      "Industrial & Mechanical",
    ],
    title: "HITACHI HVDC Valve Factory",
    year: "2026",
    area: "100,000 sq.ft",
    location: "Dammam, Saudi Arabia",
    coverImage: "/img/project-images/054/1.webp",
    galleryImages: [
      "/img/project-images/054/1.webp",
      "/img/project-images/054/2.webp",
      "/img/project-images/054/3.webp",
      "/img/project-images/054/4.webp",
      "/img/project-images/054/5.webp",
      "/img/project-images/054/6.webp",
      "/img/project-images/054/7.webp",
      "/img/project-images/054/8.webp",
      "/img/project-images/054/9.webp",
      "/img/project-images/054/10.webp",
      "/img/project-images/054/11.webp",
      "/img/project-images/054/12.webp",
      "/img/project-images/054/13.webp",
      "/img/project-images/054/14.webp",
      "/img/project-images/054/15.webp",
      "/img/project-images/054/16.webp",
      "/img/project-images/054/17.webp",
      "/img/project-images/054/18.webp",
      "/img/project-images/054/19.webp",
      "/img/project-images/054/20.webp",
      "/img/project-images/054/21.webp",
      "/img/project-images/054/22.webp",
      "/img/project-images/054/22.webp",
      "/img/project-images/054/24.webp",
      "/img/project-images/054/25.webp",
      "/img/project-images/054/26.webp",
      "/img/project-images/054/27.webp",
      "/img/project-images/054/28.webp",
      "/img/project-images/054/29.webp",
      "/img/project-images/054/30.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: ["https://youtube.com/embed/xiqGN22wiDs"],
  },

   {
    id: "project-048",
    slug: "mam-maternity-and-children-hospital",
    categoryType: [
      "Architectural & Interior",
      "Civil & Infrastructure",
      "Structural Engineering",
    ],
    title: "M.A.M Maternity and Children Hospital",
    year: "2026",
    area: "20,000 sq.ft",
    location: "Anjuman e Mahdevia, Chanchalguda, Hyderabad, India",
    coverImage: "/img/project-images/048/1.webp",
    galleryImages: [
      "/img/project-images/048/1.webp",
      "/img/project-images/048/2.webp",
      "/img/project-images/048/3.webp",
      "/img/project-images/048/4.webp",
      "/img/project-images/048/5.webp",
      "/img/project-images/048/6.webp",
      "/img/project-images/048/7.webp",
      "/img/project-images/048/8.webp",
      "/img/project-images/048/9.webp",
      "/img/project-images/048/10.webp",
      "/img/project-images/048/11.webp",
      "/img/project-images/048/12.webp",
      "/img/project-images/048/13.webp",
      "/img/project-images/048/14.webp",
      "/img/project-images/048/15.webp",
      "/img/project-images/048/16.webp",
      "/img/project-images/048/17.webp",
      "/img/project-images/048/18.webp",
      "/img/project-images/048/19.webp",
      "/img/project-images/048/20.webp",
      "/img/project-images/048/21.webp",
      "/img/project-images/048/22.webp",
      "/img/project-images/048/23.webp",
      "/img/project-images/048/24.webp",
      "/img/project-images/048/25.webp",
      "/img/project-images/048/26.webp",
      "/img/project-images/048/27.webp",
      "/img/project-images/048/28.webp",
      "/img/project-images/048/29.webp",
      "/img/project-images/048/30.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: ["https://youtube.com/embed/GieBokVZyak"],
  },

  {
    id: "project-049",
    slug: "crystal-gaming-zone",
    categoryType: [
      "Architectural & Interior",
    ],
    title: "Crystal Gaming Zone",
    year: "2026",
    area: "2,500 sq.ft",
    location: "Kishan Bagh, Hyderabad, India",
    coverImage: "/img/project-images/049/1.webp",
    galleryImages: [
      "/img/project-images/049/1.webp",
      "/img/project-images/049/2.webp",
      "/img/project-images/049/3.webp",
      "/img/project-images/049/4.webp",
      "/img/project-images/049/5.webp",
      "/img/project-images/049/6.webp",
      "/img/project-images/049/7.webp",
      "/img/project-images/049/8.webp",
      "/img/project-images/049/9.webp",
      "/img/project-images/049/10.webp",
      "/img/project-images/049/11.webp",
      "/img/project-images/049/12.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-051",
    slug: "verdi-estate",
    categoryType: [
      "Civil & Infrastructure",
    ],
    title: "Verdi Estate",
    year: "2026",
    area: "61 Villas, 8 acres",
    location: "Tukkuguda, Hyderabad, India",
    coverImage: "/img/project-images/051/1.webp",
    galleryImages: [
      "/img/project-images/051/1.webp",
      "/img/project-images/051/2.webp",
      "/img/project-images/051/3.webp",
      "/img/project-images/051/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-001",
    slug: "am-villa",
    categoryType: ["Architectural & Interior"],
    title: "AM Villa",
    year: "2026",
    location: "Malakpet, Hyderabad, Telangana, India",
    area: "10,000 sq.ft",
    coverImage:
      "/img/project-images/001/1.webp",
    galleryImages: [
      "/img/project-images/001/1.webp",
      "/img/project-images/001/2.webp",
      "/img/project-images/001/3.webp",
      "/img/project-images/001/4.webp",
      "/img/project-images/001/5.webp",
      "/img/project-images/001/6.webp",
      "/img/project-images/001/7.webp",
      "/img/project-images/001/8.webp",
      "/img/project-images/001/9.webp",
      "/img/project-images/001/10.webp",
      "/img/project-images/001/11.webp",
      "/img/project-images/001/12.webp",
      "/img/project-images/001/13.webp",
      "/img/project-images/001/14.webp",
      "/img/project-images/001/15.webp",
      "/img/project-images/001/16.webp",
      "/img/project-images/001/17.webp",
      "/img/project-images/001/18.webp",
      "/img/project-images/001/19.webp",
      "/img/project-images/001/20.webp",
      "/img/project-images/001/21.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-031",
    slug: "new-gymnasium-workout-rooms-illinius",
    categoryType: [
      "Architectural & Interior",
      "Structural Engineering",
      "BIM & MEP",
    ],
    title: "New Gymnasium & Workout Rooms Illinius",
    year: "2026",
    location: "Harvey, Chicago, USA",
    area: "12,000 sq.ft",
    coverImage: "/img/project-images/031/1.webp",
    galleryImages: [
      "/img/project-images/031/1.webp",
      "/img/project-images/031/2.webp",
      "/img/project-images/031/3.webp",
      "/img/project-images/031/4.webp",
      "/img/project-images/031/5.webp",
      "/img/project-images/031/6.webp",
      "/img/project-images/031/7.webp",
      "/img/project-images/031/8.webp",
      "/img/project-images/031/9.webp",
      "/img/project-images/031/10.webp",
      "/img/project-images/031/11.webp",
      "/img/project-images/031/12.webp",
    ],

    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

   {
    id: "project-020",
    slug: "jp-mindtree-hotel",
    categoryType: ["Architectural & Interior"],
    title: "JP Mindtree Hotel",
    year: "2026",
    location: "Madhapur, Hyderabad, Telangana, India",
    area: "20,000 sq.ft",
    coverImage: "/img/project-images/020/1.webp",
    galleryImages: [
      "/img/project-images/020/1.webp",
      "/img/project-images/020/2.webp",
      "/img/project-images/020/3.webp",
      "/img/project-images/020/4.webp",
      "/img/project-images/020/5.webp",
      "/img/project-images/020/6.webp",
      "/img/project-images/020/7.webp",
      "/img/project-images/020/8.webp",
      "/img/project-images/020/9.webp",
      "/img/project-images/020/10.webp",
      "/img/project-images/020/11.webp",
      "/img/project-images/020/12.webp",
      "/img/project-images/020/13.webp",
      "/img/project-images/020/14.webp",
      "/img/project-images/020/15.webp",
      "/img/project-images/020/16.webp",
      "/img/project-images/020/17.webp",
      "/img/project-images/020/18.webp",
      "/img/project-images/020/19.webp",
      "/img/project-images/020/20.webp",
      "/img/project-images/020/21.webp",
      "/img/project-images/020/22.webp",
      "/img/project-images/020/23.webp",
      "/img/project-images/020/24.webp",
      "/img/project-images/020/25.webp",
      "/img/project-images/020/26.webp",
      "/img/project-images/020/27.webp",
      "/img/project-images/020/28.webp",
      "/img/project-images/020/29.webp",
      "/img/project-images/020/30.webp",
      "/img/project-images/020/31.webp",
      "/img/project-images/020/32.webp",
      "/img/project-images/020/33.webp",
      "/img/project-images/020/34.webp",
      "/img/project-images/020/35.webp",
      "/img/project-images/020/36.webp",
      "/img/project-images/020/37.webp",
      "/img/project-images/020/38.webp",
      "/img/project-images/020/39.webp",
      "/img/project-images/020/40.webp",
      "/img/project-images/020/41.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-034",
    slug: "bus-station-education-city-doha-complete-mep",
    categoryType: ["BIM & MEP"],
    title: "Bus Station Education City Doha, Complete MEP",
    year: "2026",
    location: "Education City, Doha, Qatar",
    area: "",
    coverImage: "/img/project-images/034/1.webp",
    galleryImages: [
      "/img/project-images/034/1.webp",
      "/img/project-images/034/2.webp",
      "/img/project-images/034/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-003",
    slug: "aynoor-cosmetic",
    categoryType: ["Architectural & Interior"],
    title: "Aynoor Cosmetic",
    year: "2026",
    location: "Charminar, Hyderabad, Telangana, India",
    area: "300 sq.ft",
    coverImage:
      "/img/project-images/003/1.webp",
    galleryImages: [
      "/img/project-images/003/1.webp",
      "/img/project-images/003/2.webp",
      "/img/project-images/003/3.webp",
      "/img/project-images/003/4.webp",
      "/img/project-images/003/5.webp",
      "/img/project-images/003/6.webp",
      "/img/project-images/003/7.webp",
      "/img/project-images/003/8.webp",
      "/img/project-images/003/9.webp",
      "/img/project-images/003/10.webp",
      "/img/project-images/003/11.webp",
      "/img/project-images/003/12.webp",
      "/img/project-images/003/13.webp",
      "/img/project-images/003/14.webp",
      "/img/project-images/003/15.webp",
      "/img/project-images/003/16.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-047",
    slug: "nec-event-support-facility-building-neon-experience-centre",
    categoryType: [
      "Structural Engineering",
      "BIM & MEP",
      "Civil & Infrastructure",
    ],
    title: "NEC Event Support Facility Building — NEON Experience Centre",
    year: "2026",
    area: "12,000 sq.ft",
    location: "Kingdom of Saudi Arabia",
    coverImage: "/img/project-images/047/1.webp",
    galleryImages: [
      "/img/project-images/047/1.webp",
      "/img/project-images/047/2.webp",
      "/img/project-images/047/3.webp",
      "/img/project-images/047/4.webp",
      "/img/project-images/047/5.webp",
      "/img/project-images/047/6.webp",
      "/img/project-images/047/7.webp",
      "/img/project-images/047/8.webp",
      "/img/project-images/047/9.webp",
      "/img/project-images/047/10.webp",
      "/img/project-images/047/11.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-008",
    slug: "aisha-salim-hamood-al-hajri",
    categoryType: ["Architectural & Interior"],
    title: "Aisha Salim Hamood Al Hajri",
    year: "2026",
    location: "Barka Al Haram, Oman",
    area: "20,000 sq.ft",
    coverImage: "/img/project-images/008/1.webp",
    galleryImages: [
      "/img/project-images/008/1.webp",
      "/img/project-images/008/2.webp",
      "/img/project-images/008/3.webp",
      "/img/project-images/008/4.webp",
      "/img/project-images/008/5.webp",
      "/img/project-images/008/6.webp",
      "/img/project-images/008/7.webp",
    ],

    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-050",
    slug: "sohar-1-power-plant",
    categoryType: [
      "Industrial & Mechanical",
      "BIM & MEP",
      "Civil & Infrastructure",
    ],
    title: "Sohar 1 Power Plant",
    year: "2026",
    area: "",
    location: "Sohar, Oman",
    coverImage: "/img/project-images/050/1.webp",
    galleryImages: [
      "/img/project-images/050/1.webp",
      "/img/project-images/050/2.webp",
      "/img/project-images/050/3.webp",
      "/img/project-images/050/4.webp",
      "/img/project-images/050/5.webp",
      "/img/project-images/050/6.webp",
      "/img/project-images/050/7.webp",
      "/img/project-images/050/8.webp",
      "/img/project-images/050/9.webp",
      "/img/project-images/050/10.webp",
      "/img/project-images/050/11.webp",
      "/img/project-images/050/12.webp",
      "/img/project-images/050/13.webp",
      "/img/project-images/050/14.webp",
      "/img/project-images/050/15.webp",
      "/img/project-images/050/16.webp",
      "/img/project-images/050/17.webp",
      "/img/project-images/050/18.webp",

    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  
  {
    id: "project-002",
    slug: "anwar-flat",
    categoryType: ["Architectural & Interior"],
    title: "Anwar Flat",
    year: "2025",
    location: "Chanchalguda, Hyderabad, Telangana, India",
    area: "2,500 sq.ft",
    coverImage:
      "/img/project-images/002/1.webp",
    galleryImages: [
      "/img/project-images/002/1.webp",
      "/img/project-images/002/2.webp",
      "/img/project-images/002/3.webp",
      "/img/project-images/002/4.webp",
      "/img/project-images/002/5.webp",
      "/img/project-images/002/6.webp",
      "/img/project-images/002/7.webp",
      "/img/project-images/002/8.webp",
      "/img/project-images/002/9.webp",
      "/img/project-images/002/10.webp",
      "/img/project-images/002/11.webp",
      "/img/project-images/002/12.webp",
      "/img/project-images/002/13.webp",
      "/img/project-images/002/14.webp",
      "/img/project-images/002/15.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  
  {
    id: "project-004",
    slug: "rahil-attapur-3bhk-flat-interior",
    categoryType: ["Architectural & Interior"],
    title: "Rahil Attapur 3BHK Flat Interior",
    year: "2026",
    location: "Attapur, Hyderabad, Telangana, India",
    area: "1,800 sq.ft",
    coverImage:
      "/img/project-images/004/1.webp",
    galleryImages: [
      "/img/project-images/004/1.webp",
      "/img/project-images/004/2.webp",
      "/img/project-images/004/3.webp",
      "/img/project-images/004/4.webp",
      "/img/project-images/004/5.webp",
      "/img/project-images/004/6.webp",
      "/img/project-images/004/7.webp",
      "/img/project-images/004/8.webp",
      "/img/project-images/004/9.webp",
      "/img/project-images/004/10.webp",
      "/img/project-images/004/11.webp",
      "/img/project-images/004/12.webp",
      "/img/project-images/004/13.webp",
      "/img/project-images/004/14.webp",
      "/img/project-images/004/15.webp",
      "/img/project-images/004/16.webp",
      "/img/project-images/004/17.webp",
      "/img/project-images/004/18.webp",
      "/img/project-images/004/19.webp",
      "/img/project-images/004/20.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-005",
    slug: "mr-zayyid-al-sir-rushadi",
    categoryType: ["Architectural & Interior"],
    title: "MR Zayyid Al Sir Rushadi",
    year: "2023",
    location: "Barka, Oman",
    area: "15,000 sq.ft",
    coverImage: "/img/project-images/005/1.webp",
    galleryImages: [
      "/img/project-images/005/1.webp",
      "/img/project-images/005/2.webp",
      "/img/project-images/005/3.webp",
      "/img/project-images/005/4.webp",
      "/img/project-images/005/5.webp",
      "/img/project-images/005/6.webp",
      "/img/project-images/005/7.webp",
      "/img/project-images/005/8.webp",
      "/img/project-images/005/9.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-006",
    slug: "modern-elevation",
    categoryType: ["Architectural & Interior"],
    title: "Modern Elevation",
    year: "2025",
    location: "Bandlaguda, Hyderabad, Telangana, India",
    area: "4,500 sq.ft",
    coverImage: "/img/project-images/006/1.webp",
    galleryImages: [
      "/img/project-images/006/1.webp",
      "/img/project-images/006/2.webp",
      "/img/project-images/006/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-007",
    slug: "lodha-flat",
    categoryType: ["Architectural & Interior"],
    title: "LODHA Flat",
    year: "2024",
    location: "Mumbai, Maharashtra, India",
    area: "1,200 sq.ft",
    coverImage: "/img/project-images/007/1.webp",
    galleryImages: [
      "/img/project-images/007/1.webp",
      "/img/project-images/007/2.webp",
      "/img/project-images/007/3.webp",
      "/img/project-images/007/4.webp",
      "/img/project-images/007/5.webp",
      "/img/project-images/007/6.webp",
      "/img/project-images/007/7.webp",
      "/img/project-images/007/8.webp",
      "/img/project-images/007/9.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  
  {
    id: "project-009",
    slug: "ayushman-villa",
    categoryType: ["Architectural & Interior"],
    title: "Ayushman Villa",
    year: "2023",
    location: "Guwahati, Assam, India",
    area: "3,000 sq.ft",
    coverImage: "/img/project-images/009/1.webp",
    galleryImages: [
      "/img/project-images/009/1.webp",
      "/img/project-images/009/2.webp",
      "/img/project-images/009/3.webp",
      "/img/project-images/009/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-010",
    slug: "15000-sft-farmhouse",
    categoryType: ["Architectural & Interior"],
    title: "Farmhouse",
    year: "2025",
    location: "Rajendranagar, Hyderabad, Telangana, India",
    area: "15,000 sq.ft",
    coverImage: "/img/project-images/010/1.webp",
    galleryImages: [
      "/img/project-images/010/1.webp",
      "/img/project-images/010/2.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-011",
    slug: "brand-pocket-showroom",
    categoryType: ["Architectural & Interior"],
    title: "Brand Pocket Showroom",
    year: "2024",
    location: "Chaderghat, Hyderabad, Telangana, India",
    area: "1,000 sq.ft",
    coverImage: "/img/project-images/011/1.webp",
    galleryImages: [
      "/img/project-images/011/1.webp",
      "/img/project-images/011/2.webp",
      "/img/project-images/011/3.webp",
      "/img/project-images/011/4.webp",
      "/img/project-images/011/5.webp",
      "/img/project-images/011/6.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-012",
    slug: "residential-apartment",
    categoryType: ["Architectural & Interior"],
    title: "Residential Apartment",
    year: "2026",
    location: "Chanchalguda, Hyderabad, Telangana, India",
    area: "",
    coverImage: "/img/project-images/012/1.webp",
    galleryImages: [
      "/img/project-images/012/1.webp",
      "/img/project-images/012/2.webp",
      "/img/project-images/012/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-013",
    slug: "dosti-wave",
    categoryType: ["Architectural & Interior"],
    title: "Dosti Wave",
    year: "2023",
    location: "Mumbai, Maharashtra, India",
    area: "2,500 sq.ft",
    coverImage: "/img/project-images/013/1.webp",
    galleryImages: [
      "/img/project-images/013/1.webp",
      "/img/project-images/013/2.webp",
      "/img/project-images/013/3.webp",
      "/img/project-images/013/4.webp",
      "/img/project-images/013/5.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-014",
    slug: "fahad-abdul-rahim-al-balushi",
    categoryType: ["Architectural & Interior"],
    title: "Fahad Abdul Rahim Al Balushi",
    year: "2025",
    location: "Oman",
    area: "12,000 sq.ft",
    coverImage: "/img/project-images/014/1.webp",
    galleryImages: [
      "/img/project-images/014/1.webp",
      "/img/project-images/014/2.webp",
      "/img/project-images/014/3.webp",
      "/img/project-images/014/4.webp",
      "/img/project-images/014/5.webp",
      "/img/project-images/014/6.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-015",
    slug: "elevation-yakutpura",
    categoryType: ["Architectural & Interior"],
    title: "Elevation Yakutpura",
    year: "2024",
    location: "",
    area: "300 sq.yds",
    coverImage: "/img/project-images/015/1.webp",
    galleryImages: [
      "/img/project-images/015/1.webp",
      "/img/project-images/015/2.webp",
      "/img/project-images/015/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-016",
    slug: "elevation-peddapalli",
    categoryType: ["Architectural & Interior"],
    title: "Elevation Peddapalli",
    year: "2026",
    location: "Peddapalli, Telangana, India",
    area: "8,000 sq.ft",
    coverImage: "/img/project-images/016/1.webp",
    galleryImages: [
      "/img/project-images/016/1.webp",
      "/img/project-images/016/2.webp",
      "/img/project-images/016/3.webp",
      "/img/project-images/016/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-017",
    slug: "govik-industry-design",
    categoryType: ["Architectural & Interior"],
    title: "Govik Industry Design",
    year: "2023",
    location: "Mumbai, Maharashtra, India",
    area: "",
    coverImage: "/img/project-images/017/1.webp",
    galleryImages: [
      "/img/project-images/017/1.webp",
      "/img/project-images/017/2.webp",
      "/img/project-images/017/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-018",
    slug: "guest-house",
    categoryType: ["Architectural & Interior"],
    title: "Guest House",
    year: "2025",
    location: "Shamshabad, Hyderabad, Telangana, India",
    area: "500 sq.yds",
    coverImage: "/img/project-images/018/1.webp",
    galleryImages: [
      "/img/project-images/018/1.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-019",
    slug: "government-project-indira-mahila-shakti",
    categoryType: ["Architectural & Interior"],
    title: "Government Project — Indira Mahila Shakti",
    year: "2024",
    location: "Telangana, India",
    area: "36,000 stalls",
    coverImage: "/img/project-images/019/1.webp",
    galleryImages: [
      "/img/project-images/019/1.webp",
      "/img/project-images/019/2.webp",
      "/img/project-images/019/3.webp",
      "/img/project-images/019/4.webp",
      "/img/project-images/019/5.webp",
      "/img/project-images/019/6.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
 
  {
    id: "project-021",
    slug: "oakline-hotel-and-resort",
    categoryType: ["Architectural & Interior"],
    title: "Oakline Hotel and Resort",
    year: "2023",
    location: "Madhapur, Hyderabad, Telangana, India",
    area: "17,000 sq.ft",
    coverImage: "/img/project-images/021/1.webp",
    galleryImages: [
      "/img/project-images/021/1.webp",
      "/img/project-images/021/2.webp",
      "/img/project-images/021/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-022",
    slug: "khalid-salim-mohammed-al-mahadli",
    categoryType: ["Architectural & Interior"],
    title: "Khalid Salim Mohammed Al Mahadli",
    year: "2025",
    location: "Oman",
    area: "",
    coverImage: "/img/project-images/022/1.webp",
    galleryImages: [
      "/img/project-images/022/1.webp",
      "/img/project-images/022/2.webp",
      "/img/project-images/022/3.webp",
      "/img/project-images/022/4.webp",
      "/img/project-images/022/5.webp",
      "/img/project-images/022/6.webp",
      "/img/project-images/022/7.webp",
      "/img/project-images/022/8.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-023",
    slug: "majid-al-amri",
    categoryType: ["Architectural & Interior"],
    title: "Majid Al Amri",
    year: "2024",
    location: "Oman",
    area: "",
    coverImage: "/img/project-images/023/1.webp",
    galleryImages: [
      "/img/project-images/023/1.webp",
      "/img/project-images/023/2.webp",
      "/img/project-images/023/3.webp",
      "/img/project-images/023/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-024",
    slug: "masjid-e-majid",
    categoryType: ["Architectural & Interior"],
    title: "Masjid e Majid",
    year: "2026",
    location: "India",
    area: "",
    coverImage: "/img/project-images/024/1.webp",
    galleryImages: [
      "/img/project-images/024/1.webp",
      "/img/project-images/024/2.webp",
      "/img/project-images/024/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-025",
    slug: "meenakshi-silks",
    categoryType: ["Architectural & Interior"],
    title: "Meenakshi Silks",
    year: "2023",
    location: "Kukatpally, Hyderabad, Telangana, India",
    area: "3,000 sq.ft",
    coverImage: "/img/project-images/025/1.webp",
    galleryImages: [
      "/img/project-images/025/1.webp",
      "/img/project-images/025/2.webp",
      "/img/project-images/025/3.webp",
      "/img/project-images/025/4.webp",
      "/img/project-images/025/5.webp",
      "/img/project-images/025/6.webp",
      "/img/project-images/025/7.webp",
      "/img/project-images/025/8.webp",
      "/img/project-images/025/9.webp",
      "/img/project-images/025/10.webp",
      "/img/project-images/025/11.webp",
      "/img/project-images/025/12.webp",
      "/img/project-images/025/13.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-026",
    slug: "neighbourhood-villas",
    categoryType: ["Architectural & Interior"],
    title: "Neighbourhood Villas",
    year: "2025",
    location: "Kompally, Hyderabad, Telangana, India",
    area: "300 Villas",
    coverImage: "/img/project-images/026/1.webp",
    galleryImages: [
      "/img/project-images/026/1.webp",
      "/img/project-images/026/2.webp",
      "/img/project-images/026/3.webp",
      "/img/project-images/026/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-027",
    slug: "elevation-chanchalguda",
    categoryType: ["Architectural & Interior"],
    title: "Elevation",
    year: "2024",
    location: "Chanchalguda, Hyderabad, Telangana, India",
    area: "",
    coverImage: "/img/project-images/027/1.webp",
    galleryImages: [
      "/img/project-images/027/1.webp",
      "/img/project-images/027/2.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-028",
    slug: "villa-design",
    categoryType: ["Architectural & Interior"],
    title: "Villa Design",
    year: "2026",
    location: "",
    area: "",
    coverImage: "/img/project-images/028/1.webp",
    galleryImages: [
      "/img/project-images/028/1.webp",
      "/img/project-images/028/2.webp",
      "/img/project-images/028/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-029",
    slug: "neo-classic-elevation",
    categoryType: ["Architectural & Interior"],
    title: "Neo Classic Elevation",
    year: "2025",
    location: "Vikarabad, Telangana, India",
    area: "",
    coverImage: "/img/project-images/029/1.webp",
    galleryImages: [
      "/img/project-images/029/1.webp",
      "/img/project-images/029/2.webp",
      "/img/project-images/029/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-030",
    slug: "zakiya-al-balushi",
    categoryType: ["Architectural & Interior"],
    title: "Zakiya Al Balushi",
    year: "2023",
    location: "Oman",
    area: "",
    coverImage: "/img/project-images/030/1.webp",
    galleryImages: [
      "/img/project-images/030/1.webp",
      "/img/project-images/030/2.webp",
      "/img/project-images/030/3.webp",
      "/img/project-images/030/4.webp",
      "/img/project-images/030/5.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  
  {
    id: "project-032",
    slug: "warehouse-shamshabad",
    categoryType: [
      "Civil & Infrastructure",
      "Structural Engineering",
    ],
    title: "Warehouse",
    year: "2025",
    location: "Shamshabad, Hyderabad, Telangana, India",
    area: "600 sq.yds",
    coverImage: "/img/project-images/032/1.webp",
    galleryImages: [
      "/img/project-images/032/1.webp",
      "/img/project-images/032/2.webp",
      "/img/project-images/032/3.webp",
      "/img/project-images/032/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-033",
    slug: "3d-plans",
    categoryType: ["Civil & Infrastructure"],
    title: "3D Plans",
    year: "2024",
    location: "",
    area: "",
    coverImage: "/img/project-images/033/1.webp",
    galleryImages: [
      "/img/project-images/033/1.webp",
      "/img/project-images/033/2.webp",
      "/img/project-images/033/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  
  {
    id: "project-035",
    slug: "meeting-office",
    categoryType: ["BIM & MEP"],
    title: "Meeting Office",
    year: "2025",
    location: "",
    area: "",
    coverImage: "/img/project-images/035/1.webp",
    galleryImages: [
      "/img/project-images/035/1.webp",
      "/img/project-images/035/2.webp",
      "/img/project-images/035/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },
  {
    id: "project-036",
    slug: "boiler",
    categoryType: ["Industrial & Mechanical"],
    title: "Boiler Design",
    year: "2025",
    location: "Maharashtra, India",
    coverImage: "/img/project-images/036/1.webp",
    galleryImages: [
      "/img/project-images/036/1.webp",
      "/img/project-images/036/2.webp",
      "/img/project-images/036/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Industrial Equipment",
    scope: ["3D CAD Modeling and Mechanical Design"],
    projectTimeline: "10 days",
    capacity: "2 TPH",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-037",
    slug: "buggy",
    categoryType: ["Industrial & Mechanical"],
    title: "Off-Road Buggy",
    year: "2026",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/037/1.webp",
    galleryImages: [
      "/img/project-images/037/1.webp",
      "/img/project-images/037/2.webp",
      "/img/project-images/037/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Off-Road Vehicle",
    scope: ["Vehicle Frame Design", "3D CAD Modeling and Mechanical Design"],
    projectTimeline: "15 days",
    capacity: "2 person",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-038",
    slug: "concept-off-road",
    categoryType: ["Industrial & Mechanical"],
    title: "Concept Off-Road Vehicle",
    year: "2026",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/038/1.webp",
    galleryImages: [
      "/img/project-images/038/1.webp",
      "/img/project-images/038/2.webp",
      "/img/project-images/038/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Off-Road Vehicle",
    scope: ["Concept Development", "3D CAD Modeling and Vehicle Design"],
    projectTimeline: "30 days",
    capacity: "2 person",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-039",
    slug: "crusher",
    categoryType: ["Industrial & Mechanical"],
    title: "Crusher Machine",
    year: "2025",
    location: "Maharashtra, India",
    coverImage: "/img/project-images/039/1.webp",
    galleryImages: [
      "/img/project-images/039/1.webp",
      "/img/project-images/039/2.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Industrial Machinery",
    scope: ["Mechanical Design", "3D CAD Modeling and Assembly Design"],
    projectTimeline: "20 days",
    capacity: "10 TPH",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-040",
    slug: "gym-equipment",
    categoryType: ["Industrial & Mechanical"],
    title: "Gym Equipment Design",
    year: "2025",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/040/1.webp",
    galleryImages: [
      "/img/project-images/040/1.webp",
      "/img/project-images/040/2.webp",
      "/img/project-images/040/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Fitness Equipment",
    scope: ["Product Design", "3D CAD Modeling", "Mechanical Design and Prototype Development"],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-041",
    slug: "perpendicular-lift-frame",
    categoryType: ["Industrial & Mechanical"],
    title: "Perpendicular Lift Frame",
    year: "2026",
    location: "Saudi Arabia",
    coverImage: "/img/project-images/041/1.webp",
    galleryImages: [
      "/img/project-images/041/1.webp",
      "/img/project-images/041/2.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Elevator & Lifting Systems",
    scope: ["Elevator Frame Design", "Structural Analysis", "3D CAD Modeling", "Fabrication Drawings and Cutting Plan"],
    projectTimeline: "30 days",
    capacity: "8 person",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-042",
    slug: "cantilever-lift-frame",
    categoryType: ["Industrial & Mechanical"],
    title: "Cantilever Lift Frame",
    year: "2026",
    location: "Saudi Arabia",
    coverImage: "/img/project-images/042/1.webp",
    galleryImages: [
      "/img/project-images/042/1.webp",
      "/img/project-images/042/2.webp",
      "/img/project-images/042/3.webp",
      "/img/project-images/042/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Elevator & Lifting Systems",
    scope: ["Elevator Frame Design", "3D CAD Modeling", "Fabrication Drawings and Cutting Plan"],
    projectTimeline: "30 days",
    capacity: "8 person",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-043",
    slug: "rikshaw",
    categoryType: ["Industrial & Mechanical"],
    title: "Rikshaw Design",
    year: "2025",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/043/1.webp",
    galleryImages: [
      "/img/project-images/043/1.webp",
      "/img/project-images/043/2.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Three-Wheeler Vehicle",
    scope: ["Vehicle Design", "3D CAD Modeling and Mechanical Design"],
    projectTimeline: "10 days",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-044",
    slug: "shell-eco-marathon-car",
    categoryType: ["Industrial & Mechanical"],
    title: "Shell Eco Marathon Car – Bahrain Polytechnic",
    year: "2025",
    location: "Bahrain (Bahrain Polytechnic)",
    coverImage: "/img/project-images/044/1.webp",
    galleryImages: [
      "/img/project-images/044/1.webp",
      "/img/project-images/044/2.webp",
      "/img/project-images/044/3.webp",
      "/img/project-images/044/4.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Energy-Efficient Vehicle",
    scope: ["Vehicle Design", "Chassis Design", "3D CAD Modeling and Mechanical Engineering"],
    projectTimeline: "30 days",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-045",
    slug: "turbine",
    categoryType: ["Industrial & Mechanical"],
    title: "Turbine Design",
    year: "2025",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/045/1.webp",
    galleryImages: [
      "/img/project-images/045/1.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "Mechanical Power Systems",
    scope: ["3D CAD Modeling", "Mechanical Design and Component Design"],
    projectTimeline: "15 days",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-046",
    slug: "v12-engine",
    categoryType: ["Industrial & Mechanical"],
    title: "V12 Engine Design",
    year: "2026",
    location: "",
    coverImage: "/img/project-images/046/1.webp",
    galleryImages: [
      "/img/project-images/046/1.webp",
      "/img/project-images/046/2.webp",
      "/img/project-images/046/3.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "High-Performance Engine",
    scope: ["Engine Design", "3D CAD Modeling", "Assembly Design and Engineering Drawings"],
    projectTimeline: "25 days",
    capacity: "6.0 L",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-052",
    slug: "nazia-apartment",
    categoryType: [
      "Civil & Infrastructure",
      "Structural Engineering",
      "BIM & MEP",
    ],
    title: "Nazia Apartment",
    year: "2026",
    area: "2,100 sq.ft",
    location: "Hyderabad, India",
    coverImage: "/img/project-images/052/1.webp",
    galleryImages: [
      "/img/project-images/052/1.webp",
      "/img/project-images/052/2.webp",
      "/img/project-images/052/3.webp",
      "/img/project-images/052/4.webp",
      "/img/project-images/052/5.webp",
      "/img/project-images/052/6.webp",
      "/img/project-images/052/7.png",
      "/img/project-images/052/8.jpg",

    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

  {
    id: "project-053",
    slug: "g-plus-40",
    categoryType: [
      "Structural Engineering",
    ],
    title: "G+40",
    year: "2023",
    area: "",
    location: "",
    coverImage: "/img/project-images/053/1.webp",
    galleryImages: [
      "/img/project-images/053/1.webp",
      "/img/project-images/053/2.webp",
      "/img/project-images/053/3.webp",
      "/img/project-images/053/4.webp",
      "/img/project-images/053/5.webp",
      "/img/project-images/053/6.webp",
      "/img/project-images/053/7.webp",
      "/img/project-images/053/8.webp",
      "/img/project-images/053/9.webp",
      "/img/project-images/053/10.webp",
    ],
    // below data is for for future use
    shortDescription: "",
    typology: "",
    scope: [],
    projectTimeline: "",
    capacity: "",
    projectStatus: "",
    projectHighlights: [],
    googleMaps: "",
    videos: [],
  },

];

// Below is sample data
// {
//     id: "project-001",
//     slug: "crestview-boutique-hotel-hyderabad",
//      categoryType: ["Architectural & Interior"],
//     title: "Crestview Boutique Hotel",
//     year: "2023",
//     location: "Banjara Hills, Hyderabad, Telangana, India",
//     area: "68,000 sq.ft",
//     shortDescription: "",
//     typology: "Hospitality",
//     scope: [
//       "Architectural Concept & Design",
//       "Facade Design",
//       "3D Elevation Design",
//       "2D & 3D Floor Plans",
//       "Site Layout Planning",
//     ],
//     projectTimeline: "10 Months",
//     capacity: "64 Rooms",
//     projectStatus: "Completed",
//     projectHighlights: [
//       "Distinctive glass and stone facade",
//       "Efficient plot utilization on a narrow urban site",
//       "Optimized guest-room module for repeat efficiency",
//       "Coordinated architectural and structural planning",
//     ],
//     googleMaps: "https://maps.google.com/?q=Banjara+Hills+Hyderabad",
//     coverImage:
//       "https://images.unsplash.com/photo-1763251177167-85a9ca1966a8?q=80&w=1600&auto=format&fit=crop",
//     galleryImages: [
//       "https://images.unsplash.com/photo-1763251177167-85a9ca1966a8?q=80&w=1600&auto=format&fit=crop",
//       "https://images.unsplash.com/photo-1621831337128-35676ca30868?q=80&w=1600&auto=format&fit=crop",
//       "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop",
//       "https://images.unsplash.com/photo-1622109912940-2bddde35274d?q=80&w=1600&auto=format&fit=crop",
//     ],
//     videos: [
//       "https://www.youtube.com/embed/259vWFpzyHs",
//       "https://www.youtube.com/embed/259vWFpzyHs",
//     ],
// }